<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class GenerateTranslationStubs extends Command
{
    protected $signature = 'app:generate-translation-stubs';

    protected $description = 'Generate temporary PHP stub files (one per .md) so translation.io can extract strings from resources/text/*.md files';

    public function handle(): int
    {
        $files = glob(resource_path('text/*.md'));

        if (empty($files)) {
            $this->info('No .md files found in resources/text/ — nothing to generate.');

            return self::SUCCESS;
        }

        foreach ($files as $file) {
            $content = file_get_contents($file);
            $escaped = str_replace(['\\', "'"], ['\\\\', "\\'"], $content);

            $stub = implode("\n", [
                '<?php',
                '// AUTO-GENERATED by app:generate-translation-stubs — do not edit or commit.',
                '// This file is created before translation:sync runs and deleted immediately after.',
                '',
                "t('{$escaped}');",
                '',
            ]);

            $stubPath = resource_path('text/' . basename($file, '.md') . '.php');
            file_put_contents($stubPath, $stub);

            $this->info('Generated ' . $stubPath);
        }

        return self::SUCCESS;
    }
}
