<?php

namespace Database\Seeders\Prep;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;

class RoleAndPermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // create roles
        $superAdminRole = Role::create(['name' => 'Super Admin']);
        $globalViewerRole = Role::create(['name' => 'Global Viewer']);
        $programAdminRole = Role::create(['name' => 'Program Admin']);
        $programViewerRole = Role::create(['name' => 'Program Viewer']);
        $teamAdminRole = Role::create(['name' => 'Team Admin']);


        // create permissions
        $permissions = [
            ['name' => 'access admin panel'],
            ['name' => 'access program admin panel'],
            ['name' => 'view all programs'],
            ['name' => 'view all teams'],
            ['name' => 'view admin panel dashboard'],
            ['name' => 'view programs'],
            ['name' => 'maintain programs'],
            ['name' => 'view teams'],
            ['name' => 'maintain teams'],
            ['name' => 'view users'],
            ['name' => 'maintain users'],
            ['name' => 'view domains'],
            ['name' => 'maintain domains'],
            ['name' => 'view global indicators'],
            ['name' => 'maintain global indicators'],
            ['name' => 'view themes'],
            ['name' => 'maintain themes'],
            ['name' => 'view diet diversity module versions'],
            ['name' => 'maintain diet diversity module versions'],
            ['name' => 'view datasets'],
            ['name' => 'maintain datasets'],
            ['name' => 'view xlsform modules'],
            ['name' => 'maintain xlsform modules'],
            ['name' => 'view xlsform module versions'],
            ['name' => 'maintain xlsform module versions'],
            ['name' => 'view xlsform templates'],
            ['name' => 'maintain xlsform templates'],
            ['name' => 'view choice lists'],
            ['name' => 'maintain choice lists'],
            ['name' => 'view program admin panel dashboard'],
            ['name' => 'view my program'],
            ['name' => 'maintain my program'],
            ['name' => 'view survey dashboard'],
            ['name' => 'view team selection box'],
            ['name' => 'view my team'],
            ['name' => 'maintain my team'],
            ['name' => 'view download user guide'],
            ['name' => 'view my account'],
            ['name' => 'maintain my account'],
            ['name' => 'view survey country and languages'],
            ['name' => 'view select country and languages'],
            ['name' => 'maintain select country and languages'],
            ['name' => 'view survey translations'],
            ['name' => 'maintain survey translations'],
            ['name' => 'view survey locations'],
            ['name' => 'view manage location levels'],
            ['name' => 'maintain manage location levels'],
            ['name' => 'view list of farms'],
            ['name' => 'maintain list of farms'],
            ['name' => 'view context questions'],
            ['name' => 'maintain context questions'],
            ['name' => 'view place-based adaptations'],
            ['name' => 'view adapt time frame'],
            ['name' => 'maintain adapt time frame'],
            ['name' => 'view adapt diet quality module'],
            ['name' => 'maintain adapt diet quality module'],
            ['name' => 'view initial pilot'],
            ['name' => 'maintain initial pilot'],
            ['name' => 'view lisp'],
            ['name' => 'view lisp workshop'],
            ['name' => 'maintain lisp workshop'],
            ['name' => 'view customise indicators'],
            ['name' => 'view upload local indicators'],
            ['name' => 'maintain upload local indicators'],
            ['name' => 'view match with existing global indicators'],
            ['name' => 'maintain match with existing global indicators'],
            ['name' => 'view add custom survey questions'],
            ['name' => 'maintain add custom survey questions'],
            ['name' => 'view place custom questions in survey'],
            ['name' => 'maintain place custom questions in survey'],
            ['name' => 'view pilot'],
            ['name' => 'maintain pilot'],
            ['name' => 'view data collection'],
            ['name' => 'view set up the survey'],
            ['name' => 'maintain set up the survey'],
            ['name' => 'view monitor data collection'],
            ['name' => 'maintain monitor data collection'],
            ['name' => 'view download data'],
            ['name' => 'maintain download data'],
        ];


        // create all permissions, assign all permissions to Super Admin role
        // Super Admin = Admin Panel, Program Admin Panel, App Panel, with view permissions and maintain permissions
        $superAdminRole->permissions()->createMany($permissions);

        // assign permissions to Global Viewer role
        // Global Viewer = Super Admin with view permissions, without maintain permissions
        $globalViewerRole->givePermissionTo([
            'access admin panel',
            'access program admin panel',
            'view all programs',
            'view all teams',
            'view admin panel dashboard',
            'view programs',
            'view teams',
            'view users',
            'view domains',
            'view global indicators',
            'view themes',
            'view diet diversity module versions',
            'view datasets',
            'view xlsform modules',
            'view xlsform module versions',
            'view xlsform templates',
            'view choice lists',
            'view program admin panel dashboard',
            'view my program',
            'view survey dashboard',
            'view team selection box',
            'view my team',
            'view download user guide',
            'view my account',
            'maintain my account',
            'view survey country and languages',
            'view select country and languages',
            'view survey translations',
            'view survey locations',
            'view manage location levels',
            'view list of farms',
            'view context questions',
            'view place-based adaptations',
            'view adapt time frame',
            'view adapt diet quality module',
            'view initial pilot',
            'view lisp',
            'view lisp workshop',
            'view customise indicators',
            'view upload local indicators',
            'view match with existing global indicators',
            'view add custom survey questions',
            'view place custom questions in survey',
            'view pilot',
            'view data collection',
            'view set up the survey',
            'view monitor data collection',
            'view download data',
        ]);

        // assign permissions to Program Admin role
        // Program Admin = Program Admin Panel + App Panel, view permissions and maintain permissions
        $programAdminRole->givePermissionTo([
            'access program admin panel',
            'view program admin panel dashboard',
            'view my program',
            'maintain my program',
            'view survey dashboard',
            'view team selection box',
            'view my team',
            'maintain my team',
            'view download user guide',
            'view my account',
            'maintain my account',
            'view survey country and languages',
            'view select country and languages',
            'maintain select country and languages',
            'view survey translations',
            'maintain survey translations',
            'view survey locations',
            'view manage location levels',
            'maintain manage location levels',
            'view list of farms',
            'maintain list of farms',
            'view context questions',
            'maintain context questions',
            'view place-based adaptations',
            'view adapt time frame',
            'maintain adapt time frame',
            'view adapt diet quality module',
            'maintain adapt diet quality module',
            'view initial pilot',
            'maintain initial pilot',
            'view lisp',
            'view lisp workshop',
            'maintain lisp workshop',
            'view customise indicators',
            'view upload local indicators',
            'maintain upload local indicators',
            'view match with existing global indicators',
            'maintain match with existing global indicators',
            'view add custom survey questions',
            'maintain add custom survey questions',
            'view place custom questions in survey',
            'maintain place custom questions in survey',
            'view pilot',
            'maintain pilot',
            'view data collection',
            'view set up the survey',
            'maintain set up the survey',
            'view monitor data collection',
            'maintain monitor data collection',
            'view download data',
            'maintain download data',
        ]);

        // assign permissions to Program Viewer role
        // Program Viewer = Program Admin with view permissions, without maintain permissions
        $programViewerRole->givePermissionTo([
            'access program admin panel',
            'view program admin panel dashboard',
            'view my program',
            'view survey dashboard',
            'view team selection box',
            'view my team',
            'view download user guide',
            'view my account',
            'maintain my account',
            'view survey country and languages',
            'view select country and languages',
            'view survey translations',
            'view survey locations',
            'view manage location levels',
            'view list of farms',
            'view context questions',
            'view place-based adaptations',
            'view adapt time frame',
            'view adapt diet quality module',
            'view initial pilot',
            'view lisp',
            'view lisp workshop',
            'view customise indicators',
            'view upload local indicators',
            'view match with existing global indicators',
            'view add custom survey questions',
            'view place custom questions in survey',
            'view pilot',
            'view data collection',
            'view set up the survey',
            'view monitor data collection',
            'view download data',
        ]);

        // assign permissions to Team Admin role
        // Team Admin = App Panel, with view permissions and maintain permissions
        $teamAdminRole->givePermissionTo([
            'view survey dashboard',
            'view team selection box',
            'view my team',
            'maintain my team',
            'view download user guide',
            'view my account',
            'maintain my account',
            'view survey country and languages',
            'view select country and languages',
            'maintain select country and languages',
            'view survey translations',
            'maintain survey translations',
            'view survey locations',
            'view manage location levels',
            'maintain manage location levels',
            'view list of farms',
            'maintain list of farms',
            'view context questions',
            'maintain context questions',
            'view place-based adaptations',
            'view adapt time frame',
            'maintain adapt time frame',
            'view adapt diet quality module',
            'maintain adapt diet quality module',
            'view initial pilot',
            'maintain initial pilot',
            'view lisp',
            'view lisp workshop',
            'maintain lisp workshop',
            'view customise indicators',
            'view upload local indicators',
            'maintain upload local indicators',
            'view match with existing global indicators',
            'maintain match with existing global indicators',
            'view add custom survey questions',
            'maintain add custom survey questions',
            'view place custom questions in survey',
            'maintain place custom questions in survey',
            'view pilot',
            'maintain pilot',
            'view data collection',
            'view set up the survey',
            'maintain set up the survey',
            'view monitor data collection',
            'maintain monitor data collection',
            'view download data',
            'maintain download data',
        ]);
    }
}
