<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('previous_agroecology_scores', function (Blueprint $table) {
            $table->id();
            $table->timestamps();
        });


// CREATE TABLE `previous_agroecology_scores` (
//   `household_id` varchar(10) DEFAULT NULL,
//   `kobo_submission_id` varchar(9) DEFAULT NULL,
//   `latitude` varchar(6) DEFAULT NULL,
//   `longitude` varchar(6) DEFAULT NULL,
//   `sector` varchar(10) DEFAULT NULL,
//   `gender` varchar(6) DEFAULT NULL,
//   `birth_year` varchar(4) DEFAULT NULL,
//   `age` double DEFAULT NULL,
//   `farm_size` double DEFAULT NULL,
//   `recycling_1_score` double DEFAULT NULL,
//   `recycling_1_label` varchar(113) DEFAULT NULL,
//   `recycling_2_score` double DEFAULT NULL,
//   `recycling_2_label` varchar(104) DEFAULT NULL,
//   `recycling_3_score` double DEFAULT NULL,
//   `recycling_3_label` varchar(118) DEFAULT NULL,
//   `recycling_4_score` double DEFAULT NULL,
//   `recycling_4_label` varchar(1) DEFAULT NULL,
//   `recycling_5_score` double DEFAULT NULL,
//   `recycling_5_label` varchar(151) DEFAULT NULL,
//   `input_reduction_1_score` double DEFAULT NULL,
//   `input_reduction_1_label` varchar(129) DEFAULT NULL,
//   `input_reduction_2_score` double DEFAULT NULL,
//   `input_reduction_2_label` varchar(152) DEFAULT NULL,
//   `input_reduction_3_score` double DEFAULT NULL,
//   `input_reduction_4_score` double DEFAULT NULL,
//   `input_reduction_4_label` varchar(1) DEFAULT NULL,
//   `input_reduction_5_score` double DEFAULT NULL,
//   `input_reduction_5_label` varchar(88) DEFAULT NULL,
//   `input_reduction_6_score` double DEFAULT NULL,
//   `input_reduction_6_label` varchar(1) DEFAULT NULL,
//   `soil_health_score` double DEFAULT NULL,
//   `soil_health_label` varchar(29) DEFAULT NULL,
//   `animal_health_1_score` double DEFAULT NULL,
//   `animal_health_1_label` varchar(136) DEFAULT NULL,
//   `animal_health_2_score` double DEFAULT NULL,
//   `animal_health_2_label` varchar(32) DEFAULT NULL,
//   `animal_health_3_score` double DEFAULT NULL,
//   `animal_health_3_label` varchar(1) DEFAULT NULL,
//   `biodiversity_1_score` double DEFAULT NULL,
//   `biodiversity_1_label` varchar(41) DEFAULT NULL,
//   `biodiversity_2_score` double DEFAULT NULL,
//   `biodiversity_2_label` varchar(40) DEFAULT NULL,
//   `biodiversity_3_score` double DEFAULT NULL,
//   `biodiversity_3_label` varchar(1) DEFAULT NULL,
//   `biodiversity_4_score` double DEFAULT NULL,
//   `biodiversity_4_label` varchar(81) DEFAULT NULL,
//   `biodiversity_5_score` double DEFAULT NULL,
//   `biodiversity_5_label` varchar(81) DEFAULT NULL,
//   `biodiversity_6_score` double DEFAULT NULL,
//   `biodiversity_6_label` varchar(81) DEFAULT NULL,
//   `biodiversity_7_score` double DEFAULT NULL,
//   `biodiversity_7_label` varchar(27) DEFAULT NULL,
//   `biodiversity_8_score` double DEFAULT NULL,
//   `biodiversity_8_label` varchar(81) DEFAULT NULL,
//   `biodiversity_9_score` double DEFAULT NULL,
//   `biodiversity_9_label` varchar(81) DEFAULT NULL,
//   `biodiversity_10_score` double DEFAULT NULL,
//   `biodiversity_10_label` varchar(27) DEFAULT NULL,
//   `biodiversity_11_score` double DEFAULT NULL,
//   `biodiversity_11_label` varchar(81) DEFAULT NULL,
//   `synergy_1_score` double DEFAULT NULL,
//   `synergy_1_label` varchar(1) DEFAULT NULL,
//   `synergy_2_score` double DEFAULT NULL,
//   `synergy_2_label` varchar(24) DEFAULT NULL,
//   `synergy_3_score` double DEFAULT NULL,
//   `synergy_3_label` varchar(24) DEFAULT NULL,
//   `synergy_4_score` double DEFAULT NULL,
//   `synergy_4_label` varchar(32) DEFAULT NULL,
//   `synergy_5_score` double DEFAULT NULL,
//   `synergy_5_label` varchar(1) DEFAULT NULL,
//   `synergy_6_score` double DEFAULT NULL,
//   `synergy_6_label` varchar(32) DEFAULT NULL,
//   `economic_diversification_score` double DEFAULT NULL,
//   `economic_diversification_label` varchar(34) DEFAULT NULL,
//   `co_creation_knowledge_1_score` double DEFAULT NULL,
//   `co_creation_knowledge_1_label` varchar(24) DEFAULT NULL,
//   `co_creation_knowledge_2_score` double DEFAULT NULL,
//   `co_creation_knowledge_2_label` varchar(24) DEFAULT NULL,
//   `co_creation_knowledge_3_score` double DEFAULT NULL,
//   `co_creation_knowledge_3_label` varchar(24) DEFAULT NULL,
//   `co_creation_knowledge_4_score` double DEFAULT NULL,
//   `co_creation_knowledge_4_label` varchar(24) DEFAULT NULL,
//   `co_creation_knowledge_5_score` double DEFAULT NULL,
//   `co_creation_knowledge_5_label` varchar(24) DEFAULT NULL,
//   `co_creation_knowledge_6_score` double DEFAULT NULL,
//   `co_creation_knowledge_6_label` varchar(24) DEFAULT NULL,
//   `co_creation_knowledge_7_score` double DEFAULT NULL,
//   `co_creation_knowledge_7_label` varchar(21) DEFAULT NULL,
//   `social_values_diet_1_score` double DEFAULT NULL,
//   `social_values_diet_1_label` varchar(15) DEFAULT NULL,
//   `social_values_diet_2_score` double DEFAULT NULL,
//   `social_values_diet_2_label` varchar(15) DEFAULT NULL,
//   `social_values_diet_3_score` double DEFAULT NULL,
//   `social_values_diet_3_label` varchar(15) DEFAULT NULL,
//   `social_values_diet_4_score` double DEFAULT NULL,
//   `social_values_diet_4_label` varchar(15) DEFAULT NULL,
//   `fairness_1_score` double DEFAULT NULL,
//   `fairness_1_label` varchar(55) DEFAULT NULL,
//   `fairness_2_score` double DEFAULT NULL,
//   `fairness_2_label` varchar(55) DEFAULT NULL,
//   `fairness_3_score` double DEFAULT NULL,
//   `fairness_3_label` varchar(1) DEFAULT NULL,
//   `fairness_4_score` double DEFAULT NULL,
//   `fairness_4_label` varchar(23) DEFAULT NULL,
//   `fairness_5_score` double DEFAULT NULL,
//   `fairness_5_label` varchar(1) DEFAULT NULL,
//   `fairness_6_score` double DEFAULT NULL,
//   `fairness_6_label` varchar(1) DEFAULT NULL,
//   `connectivity_1_score` double DEFAULT NULL,
//   `connectivity_1_label` varchar(35) DEFAULT NULL,
//   `connectivity_2_score` double DEFAULT NULL,
//   `connectivity_2_label` varchar(35) DEFAULT NULL,
//   `connectivity_3_score` double DEFAULT NULL,
//   `connectivity_3_label` varchar(26) DEFAULT NULL,
//   `connectivity_4_score` double DEFAULT NULL,
//   `connectivity_4_label` varchar(26) DEFAULT NULL,
//   `connectivity_5_score` double DEFAULT NULL,
//   `connectivity_5_label` varchar(26) DEFAULT NULL,
//   `connectivity_6_score` double DEFAULT NULL,
//   `connectivity_6_label` varchar(26) DEFAULT NULL,
//   `governance_1_score` double DEFAULT NULL,
//   `governance_1_label` varchar(30) DEFAULT NULL,
//   `governance_2_score` double DEFAULT NULL,
//   `governance_2_label` varchar(38) DEFAULT NULL,
//   `governance_3_score` double DEFAULT NULL,
//   `governance_3_label` varchar(23) DEFAULT NULL,
//   `participation_score` varchar(1) DEFAULT NULL,
//   `participation_label` varchar(198) DEFAULT NULL,
//   `overall_recycling_score` double DEFAULT NULL,
//   `overall_input_reduction_score` double DEFAULT NULL,
//   `overall_soil_health_score` double DEFAULT NULL,
//   `overall_animal_health_score` double DEFAULT NULL,
//   `overall_biodiversity_score` double DEFAULT NULL,
//   `overall_synergy_score` double DEFAULT NULL,
//   `overall_economic_diversification_score` double DEFAULT NULL,
//   `overall_co_creation_knowledge_score` double DEFAULT NULL,
//   `overall_social_values_diet_score` double DEFAULT NULL,
//   `overall_fairness_score` double DEFAULT NULL,
//   `overall_connectivity_score` double DEFAULT NULL,
//   `overall_governance_score` double DEFAULT NULL,
//   `overall_participation_score` double DEFAULT NULL,
//   `country_id` varchar(3) DEFAULT NULL,
//   `country_code` varchar(3) DEFAULT NULL
// ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('previous_agroecology_scores');
    }
};
